---
title: "1228test"
output: 
  html_document:
    css: ['css/mystyle.css']
    includes:
      in_header: ["external/in_header/header.html"]
      before_body: ["external/before_body/bf_body.html"]
      after_body: ["external/after_body/af_body.html"]
---
```{r, eval=F, echo=F}
browseURL("http://localhost:8000/1228test.html")
```


```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext); library(sf); library(osmdata); library(rmapshaper); library(htmlwidgets); library(widgetframe); library(htmltools)
library(spData); library(colorspace)


showtext_auto(enable=TRUE) #啟用字體
#theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T, echo = TRUE)
```

```{r, eval=F, echo=F}
library(servr)
daemon_stop(
  daemon_list()
)
httd(dir=".",port=8000)
```

<object id="graph4" data="plot1.svg" type="image/svg+xml" width="100%"></object>
<div id="answer">12123</div>
