---
title: '20190925'
author: "KaEDe"
date: "2019年9月25日"
output: html_document
---

```{r}
df_gatherExample <- data.frame(
  country=c("A","B","C"),
  `1999`=c("0.7k","37k","212k"),
  `2000`=c("2k","80k","213k"),
  check.names = F
)


df_gatherExample
gather(df_gatherExample,
       `1999`,`2000`,
       key="年份",value="人口")
```

```{r}
gather(collegeData,
       contains("生"),
       key="類別",value="人數")

```

```{r}
library(readr)
df_taoyuanMarriage <- read_csv("https://data.tycg.gov.tw/opendata/datalist/datasetMeta/download?id=f95d1a33-ec56-44c5-a9ec-3afba8157e39&rid=fd2070ef-7431-4f9c-bc3a-82d7bfbcd2fb")
```
將資料「一～十二月」縮排在月份變數，而其下的對應值縮排在對數變數。
計算每個月份桃園總結婚對數。

```{r}
df_taoyuanMarriage %>%
  gather(-月份區域別,
          key="月份",value="對數") -> a
a #將原變數轉為結果，方便group

a %>%
  group_by(月份) %>%
    summarise(總結婚對數=sum(對數))
```


```{r}
df_spreadExample <- data.frame(
  id = c(1,1,1,2,2,2),
  var = c("花朶萼片長度", "學名", "總類數"),
  value = c(5.1, "setosa", 1, 
            7.0, "versicolor", 2))
```
```{r}
df_spreadExample
spread(df_spreadExample,
       var,value)
```

```{r}
df_twbankExchangeRate <- read_csv("http://www.bot.com.tw/Govinfo/opendata/csv/151/20180101-20181231-FXCRT.csv")
```

留下日期、幣別、即期買入匯率，將幣別依其貨幣名稱spread成不同欄位，其下所屬值為即期買入匯率。

```{r}
df_twbankExchangeRate

df_twbankExchangeRate %>%
  select(-即期賣出匯率) %>%
    spread(幣別,即期買入匯率)
```





