---
title: "Untitled"
author: "KaEDe"
date: "2019年12月4日"
output: html_document
---

```{r}
download.file("https://www.dropbox.com/s/2i3itbvvnamrtof/svg_example.html?dl=1",
              destfile="svg_example.html")
download.file("https://www.dropbox.com/s/w2qrri47hnury1t/plot_tree.svg?dl=1",
              destfile="plot_tree.svg")
```

```{r}
ggsave(filename = <filename.svg>, plot=<plot object name>)
```


```{r}
source("https://www.dropbox.com/s/wlv1ssxqq6n4p7u/gg_hw5_004.R?dl=1", encoding = "utf-8")
```


```{r}
file.create(".Rprofile")
file.edit(".Rprofile") 
```

```{r}
Sys.getenv("plotly_username")
Sys.getenv("plotly_api_key")
```

```{r}
gg_hw5_004 %>%
  ggplotly() ->
  pltly_hw5_004
```
```{r}
api_create(pltly_hw5_004,filename="pltly_hw5_004",fileopt="overwrite") -> Meta_pltly_hw5_004
```

```{r}
pltly_hw5_004_v1 <- api_download_plot("1","KaEDe881106")
pltly_hw5_004_v1
```




```{r}
save(pltly_hw5_004_v1,file = "12123.Rda")
```

```{r}
load("12123.Rda")
```


```{r}
p <- ggplot(mtcars, aes(x = wt, y = mpg)) +
   geom_point() + geom_smooth()
pltly_p0 <- ggplotly(p)

pltly_p0
```

```{r}
pltly_p0 %>% plotly_json()
```

```{r}
pltly_p <- 
  pltly_p0 %>% 
  style(
    traces=2:3,
    hoverinfo = "none" ### 不顯示
    ) 

pltly_p %>% layout(
  title="hovertext='none' on traces 2-3"
)
```


```{r}
pltly_p <-    
  pltly_p0 %>% 
  style(
    traces=1,
    hovertext=mtcars %>% rownames)  ### hover內容設定

pltly_p %>%
  layout(title="hovertext=<指定字串> on traces 1")
```




