---
title: '20191016'
author: "KaEDe"
date: "2019年10月16日"
output: html_document
---


```{r}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/homework2/graphData_homework2_005.Rda?raw=true"))
```



```{r}
graphData$data %>%
ggplot(aes(x=年份,y=毛額,color=國民所得_儲蓄_投資毛額))+
geom_line(aes(linetype=國民所得_儲蓄_投資毛額)) -> graphData$original


##設定長方形
graphData$events <- 
  data.frame(
    start=c(2008,2013),
    end=c(2009,2014),
    ymin=c(-Inf,-Inf),
    ymax=c(Inf,Inf),
    name=c("次貸危機","歐債危機")
  )

##加入長方形
graphData$original+
  geom_rect(
    data=graphData$events,
    mapping = 
      aes(
        xmin=start,
        xmax=end,
        ymin=ymin,
        ymax=ymax
      ),
    inherit.aes = F,alpha=0.2
  )+
  geom_text(
    data = graphData$events,
    aes(
      x=(start+end)/2,
      y=180000,
      label=name
    ),
    inherit.aes = F
  )-> graphData$improved

```

```{r}
graphData$original
graphData$improved
```


```{r}
startSalaryTopCat<- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/startSalaryTopCat.csv")

startSalaryTopCat$大職業別[2:7] %>% str_c(.,collapse="','")


startSalaryTopCat %>% filter(
  大職業別 %in% c('工業部門','礦業及土石採取業','製造業','電力及燃氣供應業','用水供應及污染整治業','營造業')
) -> startingSalary_industrial

graphList <- list()

startingSalary_industrial %>%
  filter(大職業別 !='工業部門') -> startingSalary_industrial_sub
startingSalary_industrial_sub %>%  
  ggplot(aes(x=大職業別))+
  geom_col(aes(y=`經常性薪資-薪資`))-> graphList$經常薪資_col0

graphList$經常薪資_col0
```

```{r}
startingSalary_industrial_sub %>%
  mutate(
    大職業別ordered=reorder(大職業別,
                    `經常性薪資-薪資`,order=T) # order=T才會輸出成ordered factor
  ) -> startingSalary_industrial_sub

startingSalary_industrial_sub %>%
  ggplot()+
  geom_col(
    aes(x=大職業別ordered,y=`經常性薪資-薪資`)
  ) -> graphList$經常薪資_x有排序ed_col0

graphList$經常薪資_x有排序ed_col0
```

```{r}
breaks_order <- levels(startingSalary_industrial_sub$大職業別ordered)
startingSalary_industrial_sub %>%
  ggplot()+
  geom_col(
    aes(x=大職業別,y=`經常性薪資-薪資`)
  )+
  scale_x_discrete(
    limits=breaks_order ##用limit調整排序
  ) -> graphList$經常薪資_x有排序ed_scaleLimits_col0

graphList$經常薪資_x有排序ed_scaleLimits_col0
```


```{r}
startingSalary_industrial_sub %>%  
  ggplot(aes(x=大職業別ordered,y=`經常性薪資-薪資`))+
  geom_col(width=0.7)+
  scale_x_discrete(
    limits=breaks_order
  ) -> graphList$經常薪資_x有排序ed_scaleLimits_geomWidth_col0

graphList$經常薪資_x有排序ed_scaleLimits_geomWidth_col0
```

```{r}
#把aes寫在ggplot裡面，以後不用一直寫。不要的時候就inhe....=F
startingSalary_industrial_sub %>%  
  ggplot(aes(x=大職業別ordered,y=`經常性薪資-薪資`))+
  geom_col(width=0.7)+
  scale_x_discrete(
    limits=breaks_order
  ) -> graphList$經常薪資_x有排序ed_scaleLimits_geomWidth_col0

graphList$經常薪資_x有排序ed_scaleLimits_geomWidth_col0
```

```{r}
##改變長寬
graphList$經常薪資_x有排序ed_scaleLimits_geomWidth_col0+
  theme(aspect.ratio = 1/1.3) -> 
  graphList$經常薪資_x有排序_scalLimits_gmWidth_asp0_col0

graphList$經常薪資_x有排序_scalLimits_gmWidth_asp0_col0
```

```{r}
graphList$經常薪資_x有排序ed_scaleLimits_geomWidth_col0 +
  geom_col(width=0.5) +
  scale_x_discrete(limits=breaks_order)+
  theme(aspect.ratio = 1)-> 
  graphList$經常薪資_x有排序_scalLimits_gmWidth_asp1_col0  

graphList$經常薪資_x有排序_scalLimits_gmWidth_asp1_col0
```

```{r}
graphList$經常薪資_x有排序_scalLimits_gmWidth_asp1_col0 +
  theme(
    axis.text.x=element_text(angle=45, hjust=1)
    ) -> graphList$經常薪資_x有排序_scalLimits_Width_asp_textAdj_col0

graphList$經常薪資_x有排序_scalLimits_Width_asp_textAdj_col0
```

```{r}
graphList$經常薪資_x有排序_scalLimits_gmWidth_asp1_col0 +
  coord_flip() -> graphList$經常薪資_x有排序_sclLimits_width_asp_flip_col0

graphList$經常薪資_x有排序_sclLimits_width_asp_flip_col0
```

















