---
title: '20190918'
author: "KaEDe"
date: "2019年9月18日"
output: html_document
---

```{r}
StuList <- list(
  次序=c(1,2,3,4,5,6,7,8),
  學號=c(172,214,322,425,517,833,752,114),
  姓名=c("小明","大雄","胖虎","小新","大白","阿華","小英","阿美"),
  性別=c("男","男","男","女","女","男","女","男"),
  成績=c(80,42,90,82,50,77,30,90)
  )
StuList 
as.data.frame(StuList) -> StuDFfromList
StuDFfromList
```


```{r}
StuDF <- data.frame(
  次序=c(1,2,3,4,5,6,7,8),
  學號=c(172,214,322,425,517,833,752,114),
  姓名=c("小明","大雄","胖虎","小新","大白","阿華","小英","阿美"),
  性別=c("男","男","男","女","女","男","女","男"),
  成績=c(80,42,90,82,50,77,30,90)
  )
StuDF 
```

```{r}
class(StuDF) #可以做df能做的事
typeof(StuDF) #以list儲存

class(StuList)
typeof(StuList)
```

```{r}
length(StuDF) # 從向量角度看
nrow(StuDF) # 從矩陣角度看
```

```{r}
str(StuDF)
head(StuDF)
```

以下用dplyr套件:
```{r}
StuDF
slice(StuDF,1:3)
slice(StuDF,4:5)
slice(StuDF,n()) #n() 為計算共有幾筆資料,為一interger
```
```{r}
slice(StuDF,(n()-1):n())
```

```{r}
StuDF
slice(StuDF,-5:-7) 
slice(StuDF,-(5:7)) #兩者皆[不要]5~7
```


```{r}
StuDF
slice(StuDF,c(1,4,8))
```

```{r}
library(readr)
collegeData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/103_student.csv")

str(collegeData)
slice(collegeData,c(1:4,(n()-2):n(),101:110))
```

```{r}
StuDF
mutate(StuDF,
       調分後成績=成績+10)
transmute(StuDF,
       調分後成績=成績+10) # 不保留其他變數

StuDF$調分後成績 <- StuDF$成績+10
StuDF
```

在collegeData:

新增變數男生及女生,其值為「一到四年級」所有男生及女生的加總。（男生使用dplyr, 女生不使用dplyr）

新增變數男女生比，其值為前述男生/女生。

```{r}
collegeData <- mutate(collegeData,男生=一年級男生+二年級男生+三年級男生+四年級男生)

collegeData$女生<-collegeData$一年級女生+collegeData$二年級女生+collegeData$三年級女生+collegeData$四年級女生

collegeData$男女生比 <- collegeData$男生/collegeData$女生

collegeData

```

summarise
```{r}
StuDF
summarise(StuDF,
        平均成績=mean(成績),
        最高分=max(成績),
        最低分=min(成績))

mutate(StuDF,
        平均成績=mean(成績),
        最高分=max(成績),
        最低分=min(成績))
```

若老師的調分為原始成績加上「最高最低分差距除以5」，請產生調分成績:
```{r}
StuDF$調分成績 <- StuDF$成績+(max(StuDF$成績)-min(StuDF$成績))/5
StuDF

StuDF1 <- StuDF
mutate(StuDF1,(調分成績=max(成績)+min(成績))/5)
StuDF1
```

```{r}
mutate(StuDF,
        平均成績=mean(成績),
        最高分=max(成績),
        最低分=min(成績)) -> StuDF2
StuDF2

select(StuDF2,
       次序,性別,
       contains("最"))

select(StuDF2,
       -次序,-性別,
       -contains("最"))
```

女性，且成績大於60
```{r}
StuDF[(StuDF$性別=="女") & (StuDF$成績>60),]
```

```{r}
StuDF
filter(StuDF,
       性別=="女")
filter(StuDF,
       (性別=="女" & 成績>60))
filter(StuDF,
       性別=="女",
       成績>60) # 多個AND條件可用,分隔
```

依以下各別情境，選出collegeData中符合情境的觀測值：

縣市名稱為“30 臺北市”

縣市名稱為“30 臺北市”或“01 新北市”。（使用OR|或belong to%in%）

```{r}
collegeData[collegeData$縣市名稱=="30 臺北市",]

filter(collegeData,
       縣市名稱=="30 臺北市"|
       縣市名稱=="01 新北市")
```

```{r}
group_by(StuDF,
         性別) -> StuDF_by性別

StuDF_by性別
# 使用grouped data frame
summarise(StuDF_by性別,
        平均成績=mean(成績),
        最高分=max(成績),
        最低分=min(成績))

# 使用ungrouped data frame
summarise(StuDF,
        平均成績=mean(成績),
        最高分=max(成績),
        最低分=min(成績))
```










