---
title: "每週一圖作業資料檔"
output: html_document
params:
  組員: ["彭亦楓"]  
  學號: ["410773109"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```

#### 資料處理
  
```{r data cleaning, echo=TRUE, eval=T}
##構思:五邊形分別代表德智體群美，突出中心越多，代表更充滿著該股能量
graphData <- list()

Ix <- c(cos(pi*1.3),cos(pi*1.7),cos(pi*0.1),0,cos(pi*0.9),cos(pi*1.3))
Iy <- c(sin(pi*1.3),sin(pi*1.7),sin(pi*0.1),1,sin(pi*0.9),sin(pi*1.3))

I1x <-1.2*Ix
I1y <-1.2*Iy

graphData$back <- data.frame(
  x1=I1x,
  y1=I1y,
  x2=2*I1x,
  y2=2*I1y,
  x3=3*I1x,
  y3=3*I1y,
  x4=4*I1x,
  y4=4*I1y,
  x5=5*I1x,
  y5=5*I1y,
  label=c("群","體","智","德","美","群")
) 

graphData$o <- data.frame(x=0,y=0)

graphData$I <- data.frame(
  x=c(graphData$back$x5[4]*0.88,graphData$back$x5[3]*0.73,graphData$back$x5[2]*0.3,graphData$back$x5[1]*0.66,graphData$back$x5[5]*0.47),
  y=c(graphData$back$y5[4]*0.88,graphData$back$y5[3]*0.73,graphData$back$y5[2]*0.3,graphData$back$y5[1]*0.66,graphData$back$y5[5]*0.47)
)

graphData$p1 <- data.frame(
  x= graphData$back$x1,
  y= graphData$back$y1
)

graphData$p2 <- data.frame(
  x= graphData$back$x2[c(1,3,4,5)],
  y= graphData$back$y2[c(1,3,4,5)]
)

graphData$p3 <- data.frame(
  x=graphData$back$x3[c(1,3,4)],
  y=graphData$back$y3[c(1,3,4)]
)

graphData$p4 <- data.frame(
  x=graphData$back$x4[4],
  y=graphData$back$y4[4]
)
#######儲存物件######
save(graphData, file="graphData.Rda")
```


